#! /bin/csh -f
# $Header: written by Yan Li 

if (-e /home/liyan/process_error.txt) then
   /bin/rm /home/liyan/process_error.txt
endif

set bnum = (b3203 b2716 b2969 b1355 b3244 b1720 b3303 b3255 b0078 b3311 b3313 b3324 b2977 b2661 b968 b3388 b3398)
set tnum = (t7683 t7705 t7851 t7762 t7778 t7845 t7990 t7999 t8001 t8058 t8071 t8100 t8161 t8209 t8260 t8264 t8342)

set tnumseven = (t7679 t7704 t7854 t7757 t7777 t7846 t7991 t8000 t8002 t8059 t8072 t8097 t8160 t8205 t8256 t8265 t8345)

set copypath = /data/brain_work/yan/pt_7t/3DMRSI
set datapath = /data/spore3/brain_clinical

set n = 0
foreach i ($bnum)
   foreach j ($tnum)
       if (-e ${datapath}/$i/$j) then
           echo $i/$j
           set n =  `arithmetic $n + 1`
           set n = `echo $n | cut -d"." -f1`

           if (! -e ${copypath}/$i/3t/) then
               mkdir ${copypath}/$i/3t
           endif	   

	   if (! -e ${copypath}/$i/3t/${j}_fbcomb_sum_cp_cor_sum.ddf) then
		cp ${datapath}/$i/$j/spectra/${j}_fbcomb_sum_cp_cor_sum.* ${copypath}/$i/3t
      #     else
      #          echo "$i/$j 3T spectra copied"
           endif

#	   if (! -e ${copypath}/$i/3t/Logfile) then
#                 cp ${datapath}/$i/$j/Logfile ${copypath}/$i/3t
#           endif
#	  if (! -e ${copypath}/$i/3t/$j) then
#              set a = `grep 'process_mc' ${datapath}/$i/$j/Logfile`
#              echo $a
#         else
#	      cd ${copypath}/$i/3t/
#             ln -s ${datapath}/$i/$j/$j
#        endif

        #  cd ${copypath}/$i/3t/
        #  /home/liyan/script/svs7tup/vss_7t.x ${j}_fbcomb_sum_cp_cor_sum
           if (! -e ${copypath}/$i/3t/${j}_fbcomb_sum_cp_cor_sum_vss.idf) then
              echo "$i/$j no vss"
           endif

# quantification
        cd ${copypath}/$i/3t/
	set rawname = ${j}_fbcomb_sum_cp_cor_sum_inv
	if (! -e ${rawname}.raw) then
              echo "{rawname}.raw didn't exist" >> /home/liyan/process_error.txt
        endif 

         foreach sl (3 4 5 6 7 8 9 10 11 12 13 14)

                 set fcontrol = ${j}_fbcomb_sum_cp_cor_sum_vss_sl${sl}_lc.control

                 if (-e $fcontrol) then
           #      7TMRSIQuantifyLcModel $rawname $sl 144

                 set fcontrol = Slice_${sl}_Results/${rawname}.control

      	         set rowst = `grep -i IROWST $fcontrol | cut -d"=" -f2`
                 set rowend = `grep -i IROWEN $fcontrol | cut -d"=" -f2`
                 set colst = `grep -i ICOLST $fcontrol | cut -d"=" -f2`
                 set colend = `grep -i ICOLEN $fcontrol | cut -d"=" -f2`
                 set voxsk = `grep -i NVOXSK $fcontrol | cut -d"=" -f2`
                 set nrow = `arithmetic $rowend - $rowst`
                 set nrow = `arithmetic $nrow + 1` 
                 set ncol = `arithmetic $colend - $colst`
                 set ncol = `arithmetic $ncol + 1`

                 set calnvox = `arithmetic $nrow x $ncol`
                 set calnvox = `arithmetic $calnvox - $voxsk`
                 set calnvox = `echo $calnvox | cut -d"." -f1`
 
                    set nps = `ls Slice_${sl}_Results/*.ps`

                    if (`echo ${#nps}` > 0) then
	                set nvox = `ls Slice_${sl}_Results/*.ps | wc -l`
                        if ($calnvox != $nvox) then
		           set nmiss = `arithmetic $calnvox - $nvox`
		           set nmiss = `echo $nmiss | cut -d"." -f1`	
                           echo "     Missing $nmiss ($nvox/$calnvox) voxel(s) in $i/$j/Slice$sl" >> /home/liyan/process_error.txt
                        else 
                           echo "     $nvox/$calnvox voxels in $i/$j/Slice$sl" >> /home/liyan/process_error.txt
                        endif
                    else

                      echo "      Missing  ${calnvox} voxels in $i/$j/Slice$sl" >> /home/liyan/process_error.txt
                    endif

               else
                   echo "       Missing control files from matlab in $i/$j/Slice$sl" >> /home/liyan/process_error.txt
                endif
              end






       endif
    end
end
echo $n
