#! /bin/csh -f

# $Header: written by Yan Li 

if ( $#argv < 3 ) then
      echo Usage: 2DJMRSIQuantifyLcModel rootname echotime options slice_number
      echo '           ' f: get the calibration fator from NAA
      echo '           ' c: calibration the spectra by the factor using FCALIB
      echo '           ' n: do nothing
      exit 1
endif 

#-----------------------------------
#    Initial Setup for variables
#-----------------------------------

set rname = $1
set file_dir = $PWD
set echotime = $2

if ($3 != f) then
   set ISLICE = $4
   set fpath_dir = $file_dir/Slice_${ISLICE}_Results
   mkdir $fpath_dir
else
   set fpath_dir=$file_dir
endif

#-----------------------------------
#  FILRAW,FILTAB,FILPS,FILCSV,FILCOO
#-----------------------------------
set LcM_dir = /home/liyan/dot_lcmodel

set FILRAW = ${file_dir}/${rname}.raw   
set FILTAB = ${fpath_dir}/${rname}_table
set FILPS = ${fpath_dir}/${rname}.ps    
set FILCSV = ${fpath_dir}/${rname}.csv  
set FILCOO = ${fpath_dir}/${rname}_coord
set tnum = `echo ${rname} | cut -d"_" -f1`

#---------------------------------------------------
#        Set up control files for each case
#---------------------------------------------------
head -13 ${LcM_dir}/yan/mymodel_3d7t.control  > $fpath_dir/head.control

echo " FILBAS = '/home/liyan/.lcmodel/basis-sets/sim_se${echotime}_qb37t.basis'" >> ${fpath_dir}/head.control

switch ($3)
    case f     
        echo " NCALIB= 1" >>${fpath_dir}/head.control
	echo " CHCALI(1)= 'naa'" >> ${fpath_dir}/head.control
	echo " FCALIB= 1.0" >> ${fpath_dir}/head.control
	breaksw
    case c
        echo " fcalib= 0.0012" >> ${fpath_dir}/head.control
        breaksw
endsw 
     
if ($3 != f) then
    
    echo " ISLICE= $ISLICE" >> ${fpath_dir}/head.control
    
#    cat ${tnum}_cor_sum_comb_cor_lc.control >>  ${fpath_dir}/head.control
#    cat phan_se1_tg167_cor_sum_comb_cor_lc.control >> ${fpath_dir}/head.control
#    cat volt_se_tg138_cor_sum_comb_cor_lc.control >> ${fpath_dir}/head.control
#     cat pt_se_cor_sum_comb_cor_sum_lc.control >> ${fpath_dir}/head.control
#     cat volt_se_cor_sum_comb_cor_lc.control >> ${fpath_dir}/head.control

     set tag_control = `ls *lc.control | cut -d' ' -f1`
    
     if (-e ${tag_control})  then
          echo "Adding control file from tags"
          echo "        ${tag_control}"
          cat ${tag_control} >> ${fpath_dir}/head.control
     endif

endif

echo " TITLE= '$rname'" >> ${fpath_dir}/head.control
echo " FILRAW= '$FILRAW'" >> ${fpath_dir}/head.control
echo " FILPS= '$FILPS'" >> ${fpath_dir}/head.control
echo " FILTAB= '$FILTAB'" >> ${fpath_dir}/head.control
echo " FILCSV= '$FILCSV'" >> ${fpath_dir}/head.control
echo " FILCOO= '$FILCOO'" >> ${fpath_dir}/head.control

tail -6 ${LcM_dir}/yan/mymodel_3d7t.control  > ${fpath_dir}/tail.control

cat ${fpath_dir}/head.control ${fpath_dir}/tail.control > ${fpath_dir}/$rname.control

/bin/rm -r ${fpath_dir}/head.control
/bin/rm -r ${fpath_dir}/tail.control

#----------------------------------------------
#              LcModel Analysis
#----------------------------------------------
${LcM_dir}/bin_v6/lcmodel < ${fpath_dir}/$rname.control

